FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o server .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/server .
COPY static/ ./static/
COPY textures/ ./textures/
COPY ost/ ./ost/
COPY scripts/ ./scripts/
COPY hatman.gif definitions.csv map.csv TILES.csv MUSIC.csv MUSIC_DEFS.csv ./
EXPOSE 8080
CMD ["./server"]

